Nk container styling
seanwash/rodinia-web pull request #1
Opened 2020-12-09 16:18 UTC by nabilkaz

# Description
The PR updates the basic styling used on the original website and completes the prerequisites to work on the basic authentication. There were a few extra items squeezed into the PR that could have been left out namely the date functionality on the story list item. 

![image](https://user-images.githubusercontent.com/3664197/101653968-d13a6280-39f4-11eb-8a74-ef7f2d8602ec.png)

## Nav
Created the `Nav` component with commented logic for the authentication behavior. This sets us up to add the authentication behavior into the app.

## Main layout
Create the main layout to house the `Nav` and `AboutHeading` components. The `MainLayout` component is used in the `pages/index.tsx` route and wraps the `StoryListContainer` component. 

## Global BG
Added the `bg-alabaster` as a global style to the `body` tag of the application to prevent awkward styling where content is shorter than the page window. Added a global background css component `styles/components/global-bg.css` and imported it into `styles/index.css`. I'm not sure if this was the proper way to add this globally although the Next documentation states that global styles should be imported directly to `_app.tsx` which calls `styles/index.css`.

## Story List Items: Dates
Took the liberty to add the `createdAt` to both the `StoryListItem` and firebase. To do this I also needed to define the createdAt type in `types/api.ts` on line 8 with `firebase.firestore.Timestamp`. One thing that was strange was that I couldn't access the methods on `firebase.firestore.Timestamp` object `.toDate()`. I was able to read properties from it as if it were a regular object. I thought I could push that off as a refactor if needed. Otherwise think the solution of converting seconds to milliseconds and creating a new `Date` object was a good enough solution for the time being.  I added `date-fns` to convert dates to human-readable formats.

![image](https://user-images.githubusercontent.com/3664197/101653904-bc5dcf00-39f4-11eb-8fbd-75dfe2688a01.png)

2020-12-10 05:28 UTC, seanwash requested changes
Left some comments, over all nice work!

2020-12-10 05:28 UTC, seanwash commented on layouts/MainLayout/default.tsx
> +const Default = ({ children }: React.PropsWithChildren<{}> ) => {
Insted of typing the argument here I think we should type it like `Default: React.FC`. `FC` allows for the children prop already and then we don't have to use an empty generic.

2020-12-10 05:28 UTC, seanwash commented on layouts/MainLayout/default.tsx
> +const Default = ({ children }: React.PropsWithChildren<{}> ) => {
I would also call default export `MainLayout` like the name of the file.

2020-12-10 05:28 UTC, seanwash commented on styles/index.css
> +@import "./components/global-bg.css";
I don't think you should need the `.css` filetype here.

2020-12-10 05:28 UTC, seanwash commented on types/api.ts
>  export interface Story {
Could we make sure there's an empty space between imports and exports?

2020-12-10 05:28 UTC, seanwash commented on types/api.ts
> +  // updatedAt: firebase.firestore.Timestamp;
It this commented out because it's unused?

2020-12-10 15:39 UTC, nabilkaz commented on layouts/MainLayout/default.tsx
> +const Default = ({ children }: React.PropsWithChildren<{}> ) => {
That's so much easier and gets rid of the linter error. I need to start digging into react type definitions.

2020-12-10 15:41 UTC, nabilkaz commented on types/api.ts
> +  // updatedAt: firebase.firestore.Timestamp;
Yes - I'll just remove it for the time being until we start adding editing/voting capability.

2020-12-10 15:56 UTC, seanwash commented on layouts/MainLayout/default.tsx
> +const Default = ({ children }: React.PropsWithChildren<{}> ) => {
I really only know a handful of them, I need to study up on that myself. We should create a shared learning doc on that so we can collab.

2020-12-10 15:57 UTC, seanwash commented on types/api.ts
> +  // updatedAt: firebase.firestore.Timestamp;
I usually tend to prefer deleting commented code unless you know 100% it will be used soon otherwise it tends to hang around for a while.

2020-12-12 16:26 UTC, nabilkaz commented
@seanwash Refactored useFetchStories to use SWR. Very slick 👌🏽. Resolved the linter issues. Ready to merge?

2020-12-12 16:35 UTC, seanwash commented
Love it! Merge away!

2020-12-12 16:35 UTC, seanwash approved these changes

2020-12-12 18:48 UTC, merged